export type SeedSeries = {
  slug: string;
  titleAr: string;
  titleEn: string;
  description: string;
  coverImage: string;
  author: string;
  artist: string;
  status: "ongoing" | "completed" | "hiatus";
  type: "manhwa" | "manga" | "manhua" | "novel";
  year: number;
  rating: number;
  views: number;
  likes: number;
  featured: boolean;
  trending: boolean;
  genres: string[];
  chaptersCount: number;
};

export const GENRES = [
  "أكشن",
  "مغامرات",
  "خيال",
  "دراما",
  "كوميدي",
  "رومانسي",
  "غموض",
  "إثارة",
  "رعب",
  "خارق للطبيعة",
  "قوة خارقة",
  "بطل غير إعتيادي",
  "ممثل",
  "مدرسي",
  "فنون قتالية",
  "تاريخي",
  "إيسيكاي",
  "نفسي",
];

export const SERIES: SeedSeries[] = [
  {
    slug: "i-was-immediately-mistaken-for-a-monster-genius-actor",
    titleAr: "لقد تم الخلط بيني وبين ممثل عبقري وحش على الفور",
    titleEn: "I Was Immediately Mistaken for a Monster Genius Actor",
    description:
      "في أحد الأيام، اكتسب كانغ وو جين فجأة القدرة على الدخول إلى فضاء فرعي عندما يقرأ نصًا أو سيناريو، ويصبح الشخصية بنفسه من خلال الفضاء الفرعي. لكن، بعد ذلك، في موقع الاختبار الذي اتبع صديقه إليه، صودف أنه أظهر التمثيل الذي اختبره في الفضاء الفرعي...؟ هكذا بدأت أسطورة الممثل الذي ظنّه الجميع عبقرياً بالفطرة، بينما هو في الحقيقة يعيش حياة كل شخصية يلعبها داخل فضاء غامض لا يعرف حدوده أحد!",
    coverImage: "/covers/monster-actor.jpg",
    author: "EL Bada",
    artist: "DUN DUN",
    status: "ongoing",
    type: "manhwa",
    year: 2023,
    rating: 9.1,
    views: 2845000,
    likes: 45200,
    featured: true,
    trending: true,
    genres: ["أكشن", "إثارة", "بطل غير إعتيادي", "خيال", "قوة خارقة", "غموض", "دراما", "خارق للطبيعة", "كوميدي", "ممثل"],
    chaptersCount: 42,
  },
  {
    slug: "shadow-monarch-ascension",
    titleAr: "صعود الملك الظل",
    titleEn: "Shadow Monarch: Ascension",
    description:
      "كان أضعف صياد في العالم، يُلقب بـ«سلاح البشرية الأضعف». لكن بعد حادثة مميتة داخل زنزانة مزدوجة، حصل على قدرة غامضة تتيح له رفع مستواه بلا حدود. من ظلال الموت، سيصعد ليصبح الملك الذي ترتعد منه الوحوش والملوك على حد سواء!",
    coverImage: "/covers/shadow-monarch.jpg",
    author: "Chugong",
    artist: "DUBU",
    status: "completed",
    type: "manhwa",
    year: 2021,
    rating: 9.7,
    views: 8920000,
    likes: 128000,
    featured: true,
    trending: true,
    genres: ["أكشن", "مغامرات", "خيال", "قوة خارقة", "إثارة", "بطل غير إعتيادي"],
    chaptersCount: 58,
  },
  {
    slug: "heavenly-sword-master",
    titleAr: "سيد السيف السماوي",
    titleEn: "Heavenly Sword Master",
    description:
      "بعد أن خانه أقرب أصدقائه وسقط من قمة جبل هوا، عاد مو يونغ إلى الماضي قبل عشرين عاماً وهو يحمل كل ذكريات حياته السابقة. هذه المرة، لن يكرر أخطاءه — سيتقن فنون السيف الأسطورية ويعتلي عرش عالم الموريم!",
    coverImage: "/covers/sword-master.jpg",
    author: "Baek Jin",
    artist: "Seo Han",
    status: "ongoing",
    type: "manhwa",
    year: 2022,
    rating: 8.8,
    views: 3120000,
    likes: 38400,
    featured: true,
    trending: false,
    genres: ["أكشن", "فنون قتالية", "مغامرات", "خيال", "تاريخي", "دراما"],
    chaptersCount: 36,
  },
  {
    slug: "grand-magic-academy",
    titleAr: "أكاديمية السحر العظمى",
    titleEn: "Grand Magic Academy",
    description:
      "إيلينا فتاة من عامة الشعب تمتلك موهبة سحرية لم يرَ مثلها منذ ألف عام. قُبلت في أكاديمية أركانوم العريقة حيث يتصارع أبناء النبلاء على العرش السحري. لكن خلف أسوار الأكاديمية، مؤامرة مظلمة تهدد بابتلاع العالم بأسره!",
    coverImage: "/covers/magic-academy.jpg",
    author: "Yoo Ria",
    artist: "Kang Min",
    status: "ongoing",
    type: "manhwa",
    year: 2023,
    rating: 8.5,
    views: 1870000,
    likes: 24100,
    featured: true,
    trending: true,
    genres: ["خيال", "مدرسي", "مغامرات", "رومانسي", "غموض", "دراما"],
    chaptersCount: 29,
  },
  {
    slug: "return-of-the-demon-king",
    titleAr: "عودة ملك الشياطين",
    titleEn: "Return of the Demon King",
    description:
      "بعد ألف عام من هزيمته على يد الأبطال السبعة، استيقظ ملك الشياطين في جسد فتى بشري ضعيف. الشياطين تفرقت، والأبطال صاروا أساطير، والعالم نسي الرعب. لكن العرش الأسود ما زال شاغراً... والملك عاد ليسترد ما سُلب منه!",
    coverImage: "/covers/demon-king.jpg",
    author: "Dark Lord",
    artist: "HELL Art",
    status: "ongoing",
    type: "manhwa",
    year: 2022,
    rating: 8.9,
    views: 4210000,
    likes: 52300,
    featured: false,
    trending: true,
    genres: ["أكشن", "خيال", "شيطاني", "إثارة", "مغامرات", "قوة خارقة"].map((g) =>
      g === "شيطاني" ? "خارق للطبيعة" : g
    ),
    chaptersCount: 47,
  },
  {
    slug: "the-lone-healer",
    titleAr: "المعالج الذي يقاتل وحيداً",
    titleEn: "The Lone Healer",
    description:
      "في عالم يزدرى فيه المعالجون ويُعاملون كأدوات، قرر سيو جون أن يكون مختلفاً. اكتشف أن سحر الشفاء يمكن أن يتحول لأخطر سلاح هجومي عرفه البشر. طُرد من فريقه، فأسس أسطورته وحيداً — معالج واحد ضد جيوش الوحوش!",
    coverImage: "/covers/healer-hero.jpg",
    author: "Han Seo",
    artist: "Lee Bin",
    status: "ongoing",
    type: "manhwa",
    year: 2024,
    rating: 8.3,
    views: 965000,
    likes: 12800,
    featured: false,
    trending: true,
    genres: ["أكشن", "خيال", "مغامرات", "دراما", "بطل غير إعتيادي"],
    chaptersCount: 21,
  },
  {
    slug: "contract-marriage-with-ceo",
    titleAr: "الزواج التعاقدي مع المدير",
    titleEn: "Contract Marriage with the CEO",
    description:
      "لسداد ديون عائلتها، وافقت هانا على زواج تعاقدي لمدة عام مع المدير التنفيذي البارد الذي يخفي وراء قسوته جرحاً قديماً. القاعدة الأولى: ممنوع الوقوع في الحب. لكن القلوب لا تعترف بالعقود... قصة رومانسية ستذيب قلبك!",
    coverImage: "/covers/romance-office.jpg",
    author: "Song Mi",
    artist: "Yuna",
    status: "ongoing",
    type: "manhwa",
    year: 2023,
    rating: 8.1,
    views: 1430000,
    likes: 19600,
    featured: false,
    trending: false,
    genres: ["رومانسي", "دراما", "كوميدي"],
    chaptersCount: 33,
  },
  {
    slug: "immortal-returns-after-10000-years",
    titleAr: "الخالد الذي عاد بعد 10,000 سنة",
    titleEn: "The Immortal Returns After 10,000 Years",
    description:
      "زرع لين فنغ الطاقة لعشرة آلاف عام حتى صار أقوى خالد في العوالم التسعة. لكن عندما عاد لعالمه الأصلي، لم تمضِ سوى عشر سنوات... وعائلته على وشك الانهيار. الإله الذي سحق العوالم سيحمي الآن من يحب — وويل لمن يقف في طريقه!",
    coverImage: "/covers/cultivator.jpg",
    author: "Long Xing",
    artist: "Tian Studio",
    status: "ongoing",
    type: "manhua",
    year: 2021,
    rating: 8.6,
    views: 2870000,
    likes: 31200,
    featured: false,
    trending: false,
    genres: ["أكشن", "خيال", "مغامرات", "فنون قتالية", "كوميدي"],
    chaptersCount: 64,
  },
  {
    slug: "high-school-bolt",
    titleAr: "بطل الثانوية: شرارة البرق",
    titleEn: "High School Bolt",
    description:
      "طالب ثانوية عادي صعقته صاعقة غامضة في ليلة عاصفة، ليستيقظ ويجد نفسه يتحكم بالكهرباء! مدرسته تخفي أكاديمية سرية للأبطال الخارقين، وقد تم اختياره للانضمام. لكن قوة البرق تأتي مع ثمن... وعدو قديم يتربص به!",
    coverImage: "/covers/school-hero.jpg",
    author: "Park Jin",
    artist: "Volt",
    status: "ongoing",
    type: "manhwa",
    year: 2024,
    rating: 8.0,
    views: 742000,
    likes: 9400,
    featured: false,
    trending: false,
    genres: ["أكشن", "مدرسي", "قوة خارقة", "كوميدي", "إثارة"],
    chaptersCount: 18,
  },
  {
    slug: "reincarnated-as-slime-lord",
    titleAr: "تجسدت كسيد الوحوش اللزجة",
    titleEn: "Reincarnated as the Slime Lord",
    description:
      "مات موظف عادي ليستيقظ في عالم آخر... كوحش لزج ضعيف! لكن هذا الوحش يمتلك قدرة الالتهام المطلق التي تبتلع كل شيء وتكتسب قواه. من أضعف مخلوق في الغابة العظمى إلى سيد يبني أعظم مملكة وحوش عرفها التاريخ!",
    coverImage: "/api/placeholder-cover?title=%D8%B3%D9%8A%D8%AF%20%D8%A7%D9%84%D9%88%D8%AD%D9%88%D8%B4&c1=10b981&c2=065f46",
    author: "Fuse",
    artist: "Mitz Vah",
    status: "ongoing",
    type: "manga",
    year: 2020,
    rating: 8.7,
    views: 3650000,
    likes: 44800,
    featured: true,
    trending: true,
    genres: ["إيسيكاي", "خيال", "مغامرات", "كوميدي", "أكشن"],
    chaptersCount: 52,
  },
  {
    slug: "whispers-in-the-dark",
    titleAr: "همسات في الظلام",
    titleEn: "Whispers in the Dark",
    description:
      "مبنى سكني قديم، جيران يختفون واحداً تلو الآخر، وهمسات تأتي من الجدران في الثالثة فجراً. المحققة سارة التي لا تؤمن بالأشباح ستكتشف أن بعض الأبواب يجب ألا تُفتح أبداً. رعب نفسي سيجعلك تخاف من الظلام!",
    coverImage: "/api/placeholder-cover?title=%D9%87%D9%85%D8%B3%D8%A7%D8%AA&c1=7c3aed&c2=1e1b4b",
    author: "Kuro",
    artist: "Yami",
    status: "hiatus",
    type: "manga",
    year: 2022,
    rating: 8.4,
    views: 1120000,
    likes: 15400,
    featured: false,
    trending: false,
    genres: ["رعب", "غموض", "نفسي", "إثارة", "خارق للطبيعة"],
    chaptersCount: 15,
  },
  {
    slug: "steel-alchemist-brotherhood",
    titleAr: "الخيميائي الفولاذي: الإخوة",
    titleEn: "Steel Alchemist: Brotherhood",
    description:
      "في عالم تحكمه الخيمياء وقانون التبادل المتكافئ، دفع شقيقان ثمناً باهظاً لمحاولتهما إحياء والدتهما. رحلة ملحمية للبحث عن حجر الفلاسفة واستعادة ما فقداه — قصة عن التضحية والإخوة وثمن الطموح!",
    coverImage: "/api/placeholder-cover?title=%D8%A7%D9%84%D8%AE%D9%8A%D9%85%D9%8A%D8%A7%D8%A6%D9%8A&c1=f59e0b&c2=7c2d12",
    author: "Hiromu A.",
    artist: "Hiromu A.",
    status: "completed",
    type: "manga",
    year: 2019,
    rating: 9.5,
    views: 6230000,
    likes: 89100,
    featured: false,
    trending: true,
    genres: ["أكشن", "مغامرات", "خيال", "دراما", "إثارة"],
    chaptersCount: 108,
  },
];

export const SEED_COMMENTS: { userName: string; content: string }[] = [
  { userName: "عشاق المانهوا", content: "أفضل فصل حتى الآن! الترجمة ممتازة والجودة عالية، شكراً أولمبس ستاف على المجهود الرائع" },
  { userName: "كينغ", content: "القصة تزداد إثارة مع كل فصل، لا أستطيع الانتظار للفصل القادم! متى موعد الصدور؟" },
  { userName: "ناروتو_فان", content: "الرسم تحفة فنية والأحداث نار، أنصح الكل بمتابعة هذا العمل الأسطوري" },
  { userName: "سارة", content: "بدأت القراءة أمس ووصلت لآخر فصل! الإدمان حقيقي يا جماعة، البطل شخصيته رهيبة" },
  { userName: "Shadow", content: "الحبكة ممتازة والتطور منطقي، من أفضل الأعمال المترجمة حالياً بدون منازع" },
  { userName: "يوسف", content: "شكراً على السرعة في الترجمة! موقعكم الأفضل عربياً بلا منافس، استمروا" },
];
